# Generated by Django 3.2.5 on 2021-10-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_onboard',
            field=models.BooleanField(default=False),
        ),
    ]
